# Configuration file for Minimized SKU Substitution Analysis

# Data settings
data:
  input_file: "data/raw/fresh_transactions.csv"    # Path to input transaction data
  attributes_file: "data/raw/product_attributes.csv"    # Path to product attributes data (optional)
  results_dir: "data/results/"    # Directory for final results
  filter_sparse_items: true    # Whether to remove items with insufficient data
  min_days: 30    # Minimum number of days an item must appear in data

# Analysis parameters
analysis:
  min_oos_days: 5    # Minimum number of out-of-stock days required for analysis
  top_k: 5    # Number of top substitutes to return for each item
  require_significance: true    # Whether to require statistical significance
  substitution_scope: "category"    # Scope for finding substitutes: "category", "sub_category", or "all"
  
# Price analysis
price_analysis:
  baseline_window: 30    # Window size for baseline price calculation
  min_baseline_periods: 7    # Minimum periods required for baseline calculation