# Configuration file for Fresh SKU Substitution Analysis

# Data settings
data:
  input_file: "data/raw/fresh_transactions.csv"
  attributes_file: "data/raw/product_attributes.csv"
  interim_dir: "data/interim/"
  results_dir: "data/results/"
  filter_sparse_items: true
  min_days: 30

# Analysis parameters
analysis:
  min_oos_days: 5
  top_k: 5
  weights:
    oos: 0.33
    price: 0.33
    promo: 0.33
  require_significance: true
  substitution_scope: "category"  # Options: "category", "sub_category", "all"
  
# Price analysis
price_analysis:
  baseline_window: 30
  min_baseline_periods: 7
  discount_threshold: 0.05
  
# Visualization
visualization:
  network_max_nodes: 50
  network_min_score: 0.1
  
# Reporting
reporting:
  generate_visualizations: true

# Calendar settings (optional)
calendar:
  use_korean_holidays: true
